<#
    .NOTES
    --------------------------------------------------------------------------------
     Code generated by:  K0NCTANT1N (k0nctant1n@outlook.com)
     Generated on:       2019-06-06 8:27 PM
     Generated by:       K0NCTANT1N
     Filename:           TeamViewerDeviceStatus.ps1
     VERSION:            1.2
    --------------------------------------------------------------------------------
    .DESCRIPTION
        Script generated by K0NCTANT1N using TeamViewerPSModules from PowerShell Studio 2019
#>


	<#

		.SYNOPSIS
			Powershell script to monitor the Status Devices from TeamViewer using PRTG
		
		.DESCRIPTION
			This script is intended to be used with PRTG Network Monitor (as a custom "EXE/Script Advanced" sensor).
			It will return the Status Teamviewer Device from TeamViewer.
		
		.PARAMETER UserToken
			To create the API token with User level, please do the following:
			Sign in with your TeamViewer account on the Management Console (www.login.teamviewer.com)
			Open Management Console -> Edit profile -> Apps -> Create script token. Add the permission View for Computers & Contacts.
			Use Script and Not App Token and User not Company Token.

		.PARAMETER Alias
			Is the Name of the Device seen in Teamviewer Management Console
		
		.EXAMPLE
			#PS C:\> TeamViewerDeviceStatus.ps1 "$UserToken" "$Alias"
		
		.NOTES
			You must download and install the Powershell Module To manage Teamviewer: https://www.powershellgallery.com/packages/TeamViewerPSModules/1.3.0.0
			This script must be placed into the folder: C:\Program Files\PRTG Network Monitor\Custom Sensors\EXEXML
			Now you can add a new “EXE/Script Advanced” sensor (I would recommend adding the sensor to the probe device) and select TeamViewerDeviceStatus.ps1” in the dropdown for the “EXE/Script” setting.
		.LINK
			Topic link: https://kb.paessler.com/en/topic/76285-feature-request-teamviewer-sensor

	#>
	Param (
		[string]$UserToken,
		[string]$Alias
	)

	<#
		.SYNOPSIS
			Set Teamviewer Token for All Other Functions, Also Test the connection to Teamviewer API
		
		.DESCRIPTION
			Use to Set Teamviewer Token For All Other Functions.
			Will Also use the GET /api/v1/ping API Function
		
		.PARAMETER UserToken
			Is the User Level Token that you can create from the Teamviewer Management Console
			Use Script and Not App Token and User not Company Token.
		
		.EXAMPLE
			#PS C:\> Set-TVToken -UserToken $value1
		
		.NOTES
			For more Details see Teamviewer API token Documentation
			https://www.teamviewer.com/en/for-developers/teamviewer-api/
			https://dl.tvcdn.de/integrate/TeamViewer_API_Documentation.pdf
	#>
	Set-TVToken -UserToken $UserToken

	<#
		.SYNOPSIS
			Gets All Teamviewer Device Info from Alias Can be Portion of the alias
		
		.DESCRIPTION
			Get all possible information of a Device from it's alias
		
		.PARAMETER alias
			Is the Name of the Device seen in all console
		
		.PARAMETER token
			Is the User Level Token that you can create from the Teamviewer Management Console
			Can use Set-TVToken Function will then not be nessessary to use this paramameter
		
		.EXAMPLE
			PS C:\> Get-TVDeviceInfoFromAlias -alias $value1
		
		.NOTES
			For more Details see Teamviewer API token Documentation
			https://www.teamviewer.com/en/for-developers/teamviewer-api/
			https://dl.tvcdn.de/integrate/TeamViewer_API_Documentation.pdf
	#>
	$StatusVariable = Get-TVDeviceInfoFromAlias -alias $Alias


	if ($StatusVariable | ?{ $_.online_state -eq "Online"}){
	    $value = 0
	} elseif ($StatusVariable | ?{ $_.online_state -eq "Offline"}){
	    $value = 1
	} else {
	    $value = -1
	}

	<#
	Write Results XML Output...
	#>
	Write-Host "<prtg>"
		     "<result>"
		     "<channel>Status</channel>"
		     "<value>$($value)</value>"
		     "<LimitMaxError>0</LimitMaxError>"
		     "<LimitMinError>-1</LimitMinError>"
		     "<LimitMode>1</LimitMode>"
		     "</result>"
		     "<text>Last message: $($StatusVariable)</text>"
	Write-Host "</prtg>"

	#taken from https://kb.paessler.com/en/topic/76285-feature-request-teamviewer-sensor